version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.0.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=secret
      - http.max_content_length=1g
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elastic

  cassandra:
    image: cassandra:latest
    container_name: abdata-cassandra
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    networks:
      - abdata-network
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_DC=my_dc

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=secret
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl
    depends_on:
      - cassandra
      - elasticsearch
    networks:
      - abdata-network

networks:
  elastic:
    driver: bridge
  abdata-network:
    driver: bridge